<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="mrogers40-PC" name="test.DiscardPileTest" tests="12" failures="0" timestamp="30 Apr 2017 07:28:14 GMT" time="0.038" errors="1">
  <testcase name="isValidMoveCardStack" time="0.002" classname="test.DiscardPileTest"/>
  <testcase name="setView" time="0.002" classname="test.DiscardPileTest"/>
  <testcase name="DiscardPile" time="0.002" classname="test.DiscardPileTest"/>
  <testcase name="addStack" time="0.008" classname="test.DiscardPileTest"/>
  <testcase name="pop" time="0.001" classname="test.DiscardPileTest"/>
  <testcase name="pushCardStack" time="0.007" classname="test.DiscardPileTest"/>
  <testcase name="addCard" time="0.005" classname="test.DiscardPileTest"/>
  <testcase name="isValidMoveCard" time="0.001" classname="test.DiscardPileTest"/>
  <testcase name="testUndoPop" time="0.001" classname="test.DiscardPileTest">
    <error type="java.lang.RuntimeException" message="Test not implemented">
      <![CDATA[java.lang.RuntimeException: Test not implemented
	at test.DiscardPileTest.testUndoPop(DiscardPileTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- testUndoPop -->
  <testcase name="pushCard" time="0.006" classname="test.DiscardPileTest"/>
  <testcase name="testGetCardAtLocationPoint" time="0.002" classname="test.DiscardPileTest"/>
  <testcase name="testGetNumViewableCards" time="0.001" classname="test.DiscardPileTest"/>
</testsuite> <!-- test.DiscardPileTest -->
