<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Nolans-MBP.home.gateway" name="test.CardStackTest" tests="18" failures="0" timestamp="28 Apr 2017 13:52:40 GMT" time="0.222" errors="1">
  <testcase name="testPeek" time="0.009" classname="test.CardStackTest"/>
  <testcase name="testPushCardStack" time="0.006" classname="test.CardStackTest"/>
  <testcase name="testPushCard" time="0.008" classname="test.CardStackTest"/>
  <testcase name="testPopCardStack" time="0.008" classname="test.CardStackTest"/>
  <testcase name="testLength" time="0.009" classname="test.CardStackTest"/>
  <testcase name="testIsEmpty" time="0.013" classname="test.CardStackTest"/>
  <testcase name="testGetStackCard" time="0.030" classname="test.CardStackTest"/>
  <testcase name="testPop" time="0.010" classname="test.CardStackTest"/>
  <testcase name="testGetCardAtLocationPoint" time="0.005" classname="test.CardStackTest"/>
  <testcase name="testIsValidMoveCardStack" time="0.009" classname="test.CardStackTest"/>
  <testcase name="testGetStackInt" time="0.016" classname="test.CardStackTest">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="-1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at FourRowSolitaire.CardStack.getCardAtLocation(CardStack.java:137)
	at FourRowSolitaire.CardStack.getStack(CardStack.java:232)
	at test.CardStackTest.testGetStackInt(CardStackTest.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- testGetStackInt -->
  <testcase name="testSearch" time="0.012" classname="test.CardStackTest"/>
  <testcase name="testGetCardAtLocationIntIndex" time="0.020" classname="test.CardStackTest"/>
  <testcase name="testAddStack" time="0.007" classname="test.CardStackTest"/>
  <testcase name="testAddCard" time="0.014" classname="test.CardStackTest"/>
  <testcase name="testGetBottom" time="0.022" classname="test.CardStackTest"/>
  <testcase name="testGetAvailableCards" time="0.016" classname="test.CardStackTest"/>
  <testcase name="testIsValidMoveCard" time="0.008" classname="test.CardStackTest"/>
</testsuite> <!-- test.CardStackTest -->
